ci:
  # Commit name when auto fixing PRs.
  autofix_commit_msg: |
    ci: auto fixes from pre-commit.com hooks.

    for more information, see https://pre-commit.ci

  autoupdate_commit_msg: 'ci: pre-commit autoupdate'
  autoupdate_schedule: weekly


repos:

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    name: Spell Check for en-US
    args: ["--ignore-words", "docs/translation/en-US/vocabulary/accept.txt", "-w"]
    exclude: [
      '^(docs/translation/fr-FR/|docs/translation/pt-BR/).*',
      'package-lock.json'
    ]

  - id: codespell
    name: Spell Check for fr-FR
    files: '^docs/translation/fr-FR/.*'
    args: ["-D", "docs/translation/fr-FR/vocabulary/dictionary.txt", "--ignore-words", "docs/translation/en-US/vocabulary/accept.txt", "-w"]

  - id: codespell
    name: Spell Check for pt-BR
    files: '^docs/translation/pt-BR/.*'
    args: ["-D", "docs/translation/pt-BR/vocabulary/dictionary.txt", "--ignore-words", "docs/translation/en-US/vocabulary/accept.txt", "-w"]


- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: trailing-whitespace

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.36.0
  hooks:
    - id: check-dependabot
    - id: check-github-workflows
