name: LaTeX Build


on:
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.tex'


jobs:
  LaTeX:
    name: Compile LaTeX File
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ['english', 'french', 'portuguese']

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Compile LaTeX for ${{ matrix.language }}
        uses: xu-cheng/latex-action@25080975331dc4fc8e6f1af55788e00f84f51fff #v4.0.0
        with:
          pre_compile: |
            sed -i 's/\\selectlanguage{.*}/\\selectlanguage{${{matrix.language}}}/' main.tex
          root_file: 'main.tex'
          working_directory: 'src/'
          post_compile: |
            mv main.pdf cv-${{matrix.language}}.pdf

      - name: Upload ${{ matrix.language }} CV as PDF file
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
        with:
          name: cv-${{ matrix.language }}
          path: 'src/cv-${{matrix.language}}.pdf'