name: Release


on:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  artifacts:
    name: Create Artifacts
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ['english', 'french', 'portuguese']

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Compile LaTeX for ${{ matrix.language }}
        uses: xu-cheng/latex-action@25080975331dc4fc8e6f1af55788e00f84f51fff #v4.0.0
        with:
          pre_compile: |
            sed -i 's/\\selectlanguage{.*}/\\selectlanguage{${{matrix.language}}}/' main.tex
          root_file: 'main.tex'
          working_directory: 'src/'
          post_compile: |
            mv main.pdf cv-${{matrix.language}}.pdf

      - name: Upload ${{ matrix.language }} CV as PDF file
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
        with:
          name: cv-${{ matrix.language }}
          path: 'src/cv-${{matrix.language}}.pdf'


  releaser:
    name: Create Release
    needs:
      - artifacts
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Download All Artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 #v7.0.0
        with:
          path: src/
          pattern: cv-*
          merge-multiple: true

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 #v6.2.0
        with:
          node-version: "lts/*" # latest

      - name: Install Dependencies
        run: npm clean-install

      - name: Verify Dependencies Integrity
        run: npm audit signatures

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
